import 'package:recetas_vivas/domain/enums/ingredient_category.dart';
import 'package:recetas_vivas/domain/enums/recipe_type.dart';

List<Map<String, dynamic>> healthyRecipes = [
  {
    "name": "Mayonesa",
    "videoUrl": "assets/video/mayonesa1.mp4",
    "imageUrl": "assets/images/mayonesa1.png",
    "ingredientCategory": ["mayonesa"],
    "recipeType": ["salsa"],
  },
  {
    "name": "Pancake de Remolacha",
    "videoUrl": "assets/video/pancakeRemolacha.mp4",
    "imageUrl": "assets/images/remolacha.jpg",
    "ingredientCategory": ["tortitas", "avena"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Burrito con Atún",
    "videoUrl": "assets/video/burritoAtun.mp4",
    "imageUrl": "assets/images/burritoAtun.png",
    "ingredientCategory": ["aguacate", "atun", "burrito"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Ensalada con Pollo",
    "videoUrl": "assets/video/ensaladaPollo.mp4",
    "imageUrl": "assets/images/ensaladaPollo.png",
    "ingredientCategory": ["huevo", "pollo"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Wrap de espinaca",
    "videoUrl": "assets/video/wrapEspinaca.mp4",
    "imageUrl": "assets/images/wrapEspinaca.jpg",
    "ingredientCategory": ["huevo", "espinaca", "tortitas", "burrito"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Pasta con atún",
    "videoUrl": "assets/video/pastayAtun.mp4",
    "imageUrl": "assets/images/pastayAtun.jpg",
    "ingredientCategory": ["pasta", "huevo", "atun"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Huevo y Atun",
    "videoUrl": "assets/video/huevoyAtun.mp4",
    "imageUrl": "assets/images/huevoyAtun.png",
    "ingredientCategory": ["pasta", "huevo", "atun"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Tortilla de avena",
    "videoUrl": "assets/video/tortillaAvena.mp4",
    "imageUrl": "assets/images/tortillaAvena.png",
    "ingredientCategory": ["tortitas", "huevo", "avena"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Wrap Espinaca y Huevo",
    "videoUrl": "assets/video/wrapEspinacaHuevo.mp4",
    "imageUrl": "assets/images/wrapEspinacaHuevo.png",
    "ingredientCategory": ["burrito", "huevo", "espinaca"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tostada con huevo",
    "videoUrl": "assets/video/tostadaHuevo.mp4",
    "imageUrl": "assets/images/tostadaHuevo.jpg",
    "ingredientCategory": ["tostada", "huevo", "aguacate"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Atún con pepino",
    "videoUrl": "assets/video/atunconPepino.mp4",
    "imageUrl": "assets/images/atunconPepino.png",
    "ingredientCategory": ["atun", "pepino", "aguacate", "yogurGriego"],
    "recipeType": ["cena", "almuerzo"],
  },
  {
    "name": "Tostada con huevo duro",
    "videoUrl": "assets/video/tostadaHuevoduro.mp4",
    "imageUrl": "assets/images/tostadaHuevoduro.png",
    "ingredientCategory": ["tostada", "huevo", "aguacate"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Tortilla de zanahoria",
    "videoUrl": "assets/video/tortillaZanahoria.mp4",
    "imageUrl": "assets/images/tortillaZanahoria.png",
    "ingredientCategory": ["zanahoria", "huevo", "platano"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Yogurt con manzana",
    "videoUrl": "assets/video/yoguryManzana.mp4",
    "imageUrl": "assets/images/yoguryManzana.png",
    "ingredientCategory": ["avena", "yogurGriego", "manzana"],
    "recipeType": ["desayuno", "postre"],
  },
  {
    "name": "Papas fritas saludables",
    "videoUrl": "assets/video/papasSaludables.mp4",
    "imageUrl": "assets/images/papasSaludables.png",
    "ingredientCategory": ["mayonesa"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Wrap de pollo",
    "videoUrl": "assets/video/wrapPollo.mp4",
    "imageUrl": "assets/images/wrapPollo.jpg",
    "ingredientCategory": ["pollo", "burrito"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Atún con Huevo duro",
    "videoUrl": "assets/video/atunyHuevoDuro.mp4",
    "imageUrl": "assets/images/atunyHuevoDuro.png",
    "ingredientCategory": ["atun", "huevo"],
    "recipeType": ["cena"],
  },
  {
    "name": "Atún con pepino",
    "videoUrl": "assets/video/atunyPepino.mp4",
    "imageUrl": "assets/images/atunyPepino.png",
    "ingredientCategory": ["atun", "aguacate", "pepino"],
    "recipeType": ["cena"],
  },
  {
    "name": "Yogurt griego",
    "videoUrl": "assets/video/yogurtGriego.mp4",
    "imageUrl": "assets/images/yogurtGriego.png",
    "ingredientCategory": ["avena", "yogurGriego"],
    "recipeType": ["desayuno", "postre"],
  },
  {
    "name": "Arroz de coliflor",
    "videoUrl": "assets/video/arrozColiflor.mp4",
    "imageUrl": "assets/images/arrozColiflor.png",
    "ingredientCategory": ["brocoli"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Yogurt con Banana/Melon",
    "videoUrl": "assets/video/yogurBananaMelon.mp4",
    "imageUrl": "assets/images/yogurBananaMelon.png",
    "ingredientCategory": ["yogurGriego", "avena"],
    "recipeType": ["desayuno", "postre"],
  },
  {
    "name": "Wrap de Brócoli",
    "videoUrl": "assets/video/wrapBrocoli.mp4",
    "imageUrl": "assets/images/wrapBrocoli.png",
    "ingredientCategory": ["huevo", "brocoli", "tortitas", "burrito"],
    "recipeType": ["cena"],
  },
  {
    "name": "Plátano con Huevo",
    "videoUrl": "assets/video/platanoHuevo.mp4",
    "imageUrl": "assets/images/platanoHuevo.png",
    "ingredientCategory": ["platano", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Manzana revuelta de Avena",
    "videoUrl": "assets/video/manzanaenAvena.mp4",
    "imageUrl": "assets/images/manzanaenAvena.png",
    "ingredientCategory": ["avena", "huevo", "manzana"],
    "recipeType": ["desayuno", "postre"],
  },
  {
    "name": "Pescado con pepino",
    "videoUrl": "assets/video/pescadoyPepino.mp4",
    "imageUrl": "assets/images/pescadoyPepino.png",
    "ingredientCategory": ["pescado", "pepino"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Platano asado con huevos",
    "videoUrl": "assets/video/platanoasadoHuevos.mp4",
    "imageUrl": "assets/images/platanoasadoHuevos.png",
    "ingredientCategory": ["huevo", "platano", "aguacate"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Mayonesa 2",
    "videoUrl": "assets/video/mayonesa2.mp4",
    "imageUrl": "assets/images/mayonesa2.png",
    "ingredientCategory": ["mayonesa"],
    "recipeType": ["salsa"],
  },
  {
    "name": "Pancake de manzana",
    "videoUrl": "assets/video/pancakeManzana.mp4",
    "imageUrl": "assets/images/pancakeManzana.png",
    "ingredientCategory": ["manzana", "avena", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Ensalada de Huevo",
    "videoUrl": "assets/video/ensaladaHuevo.mp4",
    "imageUrl": "assets/images/ensaladaHuevo.png",
    "ingredientCategory": ["huevo"],
    "recipeType": ["cena"],
  },
  {
    "name": "Mayonesa 3",
    "videoUrl": "assets/video/mayonesa3.mp4",
    "imageUrl": "assets/images/mayonesa3.png",
    "ingredientCategory": ["mayonesa"],
    "recipeType": ["salsa"],
  },
  {
    "name": "Pasta con Pollo",
    "videoUrl": "assets/video/pastaPollo.mp4",
    "imageUrl": "assets/images/pastaPollo.jpg",
    "ingredientCategory": ["pasta", "pollo", "brocoli", "yogurGriego"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Burrito de Huevo duro",
    "videoUrl": "assets/video/burritoHuevoDuro.mp4",
    "imageUrl": "assets/images/burritoHuevoDuro.png",
    "ingredientCategory": ["huevo", "burrito", "aguacate"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Pancake de Espinaca entera",
    "videoUrl": "assets/video/pancakeEspinacaEntera.mp4",
    "imageUrl": "assets/images/pancakeEspinacaEntera.png",
    "ingredientCategory": ["huevo", "espinaca", "avena", "tortitas"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Pasta con Atún",
    "videoUrl": "assets/video/pastaAtun.mp4",
    "imageUrl": "assets/images/pastaAtun.png",
    "ingredientCategory": ["pasta", "atun", "aguacate", "yogurGriego"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Huevo y Calabacin",
    "videoUrl": "assets/video/huevoCalabacin.mp4",
    "imageUrl": "assets/images/huevoCalabacin.png",
    "ingredientCategory": ["huevo", "zanahoria", "calabacin", "tortitas"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tostada de Atún",
    "videoUrl": "assets/video/tostadaAtun.mp4",
    "imageUrl": "assets/images/tostadaAtun.png",
    "ingredientCategory": [
      "huevo",
      "atun",
      "yogurGriego",
      "aguacate",
      "tostada",
    ],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tostada de Espinaca",
    "videoUrl": "assets/video/tostadaEspinaca.mp4",
    "imageUrl": "assets/images/tostadaEspinaca.png",
    "ingredientCategory": ["huevo", "espinaca", "tostada"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Wrap con Tortilla de huevo",
    "videoUrl": "assets/video/wrapTortillaHuevo.mp4",
    "imageUrl": "assets/images/wrapTortillaHuevo.png",
    "ingredientCategory": ["espinaca", "huevo", "aguacate", "burrito"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Brócoli aplastado",
    "videoUrl": "assets/video/brocoliAplastado.mp4",
    "imageUrl": "assets/images/brocoliAplastado.png",
    "ingredientCategory": ["brocoli"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Plátano con Atún",
    "videoUrl": "assets/video/platanoconAtun.mp4",
    "imageUrl": "assets/images/platanoconAtun.png",
    "ingredientCategory": ["platano", "pepino", "atun"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Tortilla de Coliflor",
    "videoUrl": "assets/video/tortaColiflor.mp4",
    "imageUrl": "assets/images/tortaColiflor.png",
    "ingredientCategory": ["brocoli", "huevo"],
    "recipeType": ["cena", "almuerzo"],
  },
  {
    "name": "Tortilla de Avena pura",
    "videoUrl": "assets/video/tortillaAvenapura.mp4",
    "imageUrl": "assets/images/tortillaAvenapura.png",
    "ingredientCategory": ["avena", "aguacate", "huevo"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Arepa de Avena",
    "videoUrl": "assets/video/arepaAvenaV.mp4",
    "imageUrl": "assets/images/arepaAvenaI.png",
    "ingredientCategory": ["huevo", "atun", "mostaza", "yogurGriego", "avena"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Empanada de Manzana",
    "videoUrl": "assets/video/empanadaManzana.mp4",
    "imageUrl": "assets/images/empanadaManzanaI.png",
    "ingredientCategory": ["manzana", "huevo", "tostada"],
    "recipeType": ["postre", "desayuno"],
  },
  {
    "name": "Flautas de Pollo",
    "videoUrl": "assets/video/flautasPollo.mp4",
    "imageUrl": "assets/images/flautasPolloI.png",
    "ingredientCategory": [
      "pollo",
      "yogurGriego",
      "mostaza",
      "burrito",
      "aguacate",
    ],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Guacamole para Tostada",
    "videoUrl": "assets/video/guacamoleTostada.mp4",
    "imageUrl": "assets/images/guacamoleTostadaI.png",
    "ingredientCategory": ["aguacate", "garbanzo", "tostada"],
    "recipeType": ["desayuno", "salsa"],
  },
  {
    "name": "Tortilla de Atún",
    "videoUrl": "assets/video/tortillaAtun.mp4",
    "imageUrl": "assets/images/tortillaAtunI.png",
    "ingredientCategory": ["atun", "avena", "huevo"],
    "recipeType": ["cena"],
  },
  {
    "name": "Torta de brócoli",
    "videoUrl": "assets/video/tortitaBlocoliV.mp4",
    "imageUrl": "assets/images/tortitaBrocoliI.png",
    "ingredientCategory": ["brocoli", "huevo", "avena"],
    "recipeType": ["cena"],
  },
  {
    "name": "Tostada de atún y huevo",
    "videoUrl": "assets/video/tostadaHuevAtunV.mp4",
    "imageUrl": "assets/images/tostadaHuevAtunI.png",
    "ingredientCategory": ["atun", "huevo", "yogurGriego"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Yogurt griego con Arroz",
    "videoUrl": "assets/video/yogurtArrozV.mp4",
    "imageUrl": "assets/images/yogurtArrozI.png",
    "ingredientCategory": ["yogurGriego"],
    "recipeType": ["postre"],
  },
  {
    "name": "Yogurt Griego y Zanahoria",
    "videoUrl": "assets/video/yogurtZanahoriaV.mp4",
    "imageUrl": "assets/images/yogurtZanahoriaI.png",
    "ingredientCategory": ["yogurGriego", "manzana", "avena", "zanahoria"],
    "recipeType": ["desayuno", "postre"],
  },
  {
    "name": "Tortilla de Coliflor (2)",
    "videoUrl": "assets/video/tortitasColiflor.mp4",
    "imageUrl": "assets/images/tortitasColiflor.png",
    "ingredientCategory": ["brocoli", "huevo", "tortitas"],
    "recipeType": ["cena"],
  },
  {
    "name": "Pollo en Salsa",
    "videoUrl": "assets/video/polloenSalsa.mp4",
    "imageUrl": "assets/images/polloenSalsa.png",
    "ingredientCategory": ["pollo"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Tortilla de Linaza",
    "videoUrl": "assets/video/tortillaLinaza.mp4",
    "imageUrl": "assets/images/tortillaLinaza.png",
    "ingredientCategory": ["linaza"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tostada con Espinaca",
    "videoUrl": "assets/video/tostadaconEspinaca.mp4",
    "imageUrl": "assets/images/tostadaconEspinaca.png",
    "ingredientCategory": ["tostada", "huevo", "espinaca", "airFryer"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Pizza de Coliflor",
    "videoUrl": "assets/video/pizzaColiflor.mp4",
    "imageUrl": "assets/images/pizzaColiflor.png",
    "ingredientCategory": ["brocoli", "avena", "huevo"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Chips de Platano",
    "videoUrl": "assets/video/platanitos.mp4",
    "imageUrl": "assets/images/platanitos.png",
    "ingredientCategory": ["aguacate", "platano", "airFryer"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Quinua con Atún",
    "videoUrl": "assets/video/quinuaconAtun.mp4",
    "imageUrl": "assets/images/quinuaconAtun.png",
    "ingredientCategory": ["atun", "aguacate", "huevo", "quinua"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Tortilla de Atún y Zanahoria",
    "videoUrl": "assets/video/tortaAtunyZanahoria.mp4",
    "imageUrl": "assets/images/tortaAtunyZanahoria.png",
    "ingredientCategory": ["huevo", "atun", "zanahoria"],
    "recipeType": ["cena"],
  },
  {
    "name": "Tortilla de lenteja",
    "videoUrl": "assets/video/tortitaLentejas.mp4",
    "imageUrl": "assets/images/tortitaLentejas.png",
    "ingredientCategory": ["lentejas"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Pasta con espinaca",
    "videoUrl": "assets/video/pastayEspinaca.mp4",
    "imageUrl": "assets/images/pastayEspinaca.png",
    "ingredientCategory": ["pasta", "espinaca"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Pasta con Coliflor",
    "videoUrl": "assets/video/pastayColiflor.mp4",
    "imageUrl": "assets/images/pastayColiflor.png",
    "ingredientCategory": ["pasta", "brocoli"],
    "recipeType": ["almuerzo"],
  },
  {
    "name": "Pan de Lentejas",
    "videoUrl": "assets/video/panLentejas.mp4",
    "imageUrl": "assets/images/panLentejas.png",
    "ingredientCategory": ["huevo", "lentejas"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tortitas de Brócoli",
    "videoUrl": "assets/video/pancitoBrocoli_Queso.mp4",
    "imageUrl": "assets/images/pancitoBrocoli_Queso.png",
    "ingredientCategory": ["brocoli"],
    "recipeType": ["cena"],
  },
  {
    "name": "Burrito con Brócoli",
    "videoUrl": "assets/video/burritoConBrocoli.mp4",
    "imageUrl": "assets/images/burritoConBrocoli.png",
    "ingredientCategory": ["brocoli", "huevo", "burrito"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Burrito cuadrado",
    "videoUrl": "assets/video/burritoCuadrado.mp4",
    "imageUrl": "assets/images/burritoCuadrado.png",
    "ingredientCategory": ["burrito", "huevo"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Burrito con espinacas",
    "videoUrl": "assets/video/burritodeEspinacas.mp4",
    "imageUrl": "assets/images/burritodeEspinacas.png",
    "ingredientCategory": ["espinaca", "atun", "huevo", "burrito"],
    "recipeType": ["cena"],
  },
  {
    "name": "Burrito en pedazos",
    "videoUrl": "assets/video/burritoPedazos.mp4",
    "imageUrl": "assets/images/burritoPedazos.png",
    "ingredientCategory": ["burrito", "airFryer"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Ensalada de garbanzos",
    "videoUrl": "assets/video/ensaladaGarbanzos.mp4",
    "imageUrl": "assets/images/ensaladaGarbanzos.png",
    "ingredientCategory": ["garbanzo", "zanahoria", "atun"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Wrap de atún cremoso",
    "videoUrl": "assets/video/wrap_de_atun_cremoso.mp4",
    "imageUrl": "assets/images/wrap_de_atun_cremoso.png",
    "ingredientCategory": ["burrito", "atun", "quesoCrema", "aguacate"],
    "recipeType": ["cena"],
  },
  {
    "name": "Arepa de quinua",
    "videoUrl": "assets/video/arepadequinua.mp4",
    "imageUrl": "assets/images/arepadequinua.png",
    "ingredientCategory": [
      "aguacate",
      "yogurGriego",
      "pollo",
      "zanahoria",
      "quinua",
    ],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Arroz de coliflor pintado",
    "videoUrl": "assets/video/arroz_de_coliflorPintado.mp4",
    "imageUrl": "assets/images/arroz_de_coliflorPintado.png",
    "ingredientCategory": ["brocoli", "zanahoria"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Pan de espinaca y avena",
    "videoUrl": "assets/video/pan_de_espinaca_y_avena.mp4",
    "imageUrl": "assets/images/pan_de_espinaca_y_avena.png",
    "ingredientCategory": ["espinaca", "avena", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Wrap de pollo cremoso",
    "videoUrl": "assets/video/wrap_de_pollo_cremoso.mp4",
    "imageUrl": "assets/images/wrap_de_pollo_cremoso.png",
    "ingredientCategory": ["burrito", "pollo"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Hotcakes esponjosos de avena",
    "videoUrl": "assets/video/hotcakes_esponjosos_de_avena.mp4",
    "imageUrl": "assets/images/hotcakes_esponjosos_de_avena.png",
    "ingredientCategory": ["avena", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Pizza de calabacin",
    "videoUrl": "assets/video/pizza_de_calabacin.mp4",
    "imageUrl": "assets/images/pizza_de_calabacin.png",
    "ingredientCategory": ["calabacin", "huevo"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Pan de linaza",
    "videoUrl": "assets/video/pan_de_linaza.mp4",
    "imageUrl": "assets/images/pan_de_linaza.png",
    "ingredientCategory": ["linaza", "huevo"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Pastel de Yogurt",
    "videoUrl": "assets/video/pastel_de_yogurt.mp4",
    "imageUrl": "assets/images/pastel_de_yogurt.png",
    "ingredientCategory": ["platano", "huevo", "yogurGriego"],
    "recipeType": ["postre"],
  },
  {
    "name": "Ensalada de pepino cremoso",
    "videoUrl": "assets/video/ensalada_pepino.mp4",
    "imageUrl": "assets/images/ensalada_pepino.png",
    "ingredientCategory": ["pepino", "aguacate", "atun", "quesoCrema"],
    "recipeType": ["cena"],
  },
  {
    "name": "Mayonesa sin aceite",
    "videoUrl": "assets/video/mayonesa_sin_aceite.mp4",
    "imageUrl": "assets/images/mayonesa_sin_aceite.png",
    "ingredientCategory": ["mayonesa"],
    "recipeType": ["salsa"],
  },
  {
    "name": "Croquetas de calabacin",
    "videoUrl": "assets/video/croquetas_calabacin.mp4",
    "imageUrl": "assets/images/croquetas_calabacin.png",
    "ingredientCategory": ["calabacin", "avena", "huevo", "tortitas"],
    "recipeType": ["cena"],
  },
  {
    "name": "Wrap de Atún",
    "videoUrl": "assets/video/wrapdeAtun.mp4",
    "imageUrl": "assets/images/wrapdeAtun.png",
    "ingredientCategory": ["atun", "huevo"],
    "recipeType": ["cena"],
  },
  {
    "name": "Mini tortillas de zanahoria",
    "videoUrl": "assets/video/miniTortillas_zanahoria.mp4",
    "imageUrl": "assets/images/miniTortillas_zanahoria.png",
    "ingredientCategory": ["huevo", "zanahoria", "pollo", "aguacate"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Wrap de Quinua",
    "videoUrl": "assets/video/wrapdeQuinua.mp4",
    "imageUrl": "assets/images/wrapdeQuinua.png",
    "ingredientCategory": ["quinua", "huevo", "aguacate"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Quinua con huevo",
    "videoUrl": "assets/video/quinoaconHuevo.mp4",
    "imageUrl": "assets/images/quinoaconHuevo.png",
    "ingredientCategory": [
      "quinua",
      "brocoli",
      "zanahoria",
      "calabacin",
      "huevo",
    ],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Platano y huevo",
    "videoUrl": "assets/video/platanoyHuevo.mp4",
    "imageUrl": "assets/images/platanoyHuevo.png",
    "ingredientCategory": ["platano", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Patacones saludables",
    "videoUrl": "assets/video/pataconesSaludables.mp4",
    "imageUrl": "assets/images/pataconesSaludables.png",
    "ingredientCategory": ["airFryer", "platano"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Pan keto",
    "videoUrl": "assets/video/panKeto.mp4",
    "imageUrl": "assets/images/panKeto.png",
    "ingredientCategory": ["huevo", "yogurGriego"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Ensalada de Lechuga y Huevos",
    "videoUrl": "assets/video/ensaladaLechugaHuevos.mp4",
    "imageUrl": "assets/images/ensaladaLechugaHuevos.png",
    "ingredientCategory": ["huevo"],
    "recipeType": ["cena"],
  },
  {
    "name": "Mayonesa para diabeticos",
    "videoUrl": "assets/video/MayonesaDiabeticos.mp4",
    "imageUrl": "assets/images/MayonesaDiabeticos.png",
    "ingredientCategory": ["aguacate", "huevo"],
    "recipeType": ["salsa"],
  },
  {
    "name": "Arepa de Plátano",
    "videoUrl": "assets/video/arepaPlatano.mp4",
    "imageUrl": "assets/images/arepaPlatano.png",
    "ingredientCategory": ["platano", "zanahoria"],
    "recipeType": ["desayuno", "cena"],
  },
  {
    "name": "Tostadas de zanahoria",
    "videoUrl": "assets/video/tostadasZanahoria.mp4",
    "imageUrl": "assets/images/tostadasZanahoria.png",
    "ingredientCategory": ["avena", "zanahoria", "quesoCrema", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Huevos fritos y platano",
    "videoUrl": "assets/video/huevosFritosyPlatano.mp4",
    "imageUrl": "assets/images/huevosFritosyPlatano.png",
    "ingredientCategory": ["airFryer", "aguacate", "huevo", "platano"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Roll de Aguacate",
    "videoUrl": "assets/video/rollAguacate.mp4",
    "imageUrl": "assets/images/rollAguacate.png",
    "ingredientCategory": ["burrito", "aguacate", "huevo", "pollo"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Pancakes de plátano",
    "videoUrl": "assets/video/pancakesPlatano.mp4",
    "imageUrl": "assets/images/pancakesPlatano.png",
    "ingredientCategory": ["platano", "huevo"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Tortillas de quinoa y remolacha",
    "videoUrl": "assets/video/TortillasQuinoaRemolacha.mp4",
    "imageUrl": "assets/images/TortillasQuinoaRemolacha.png",
    "ingredientCategory": ["burrito", "quinua", "remolacha"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Tostada de espinaca y avena",
    "videoUrl": "assets/video/tostadaEspinacaAvena.mp4",
    "imageUrl": "assets/images/tostadaEspinacaAvena.png",
    "ingredientCategory": ["espinaca", "avena", "huevo", "tostada"],
    "recipeType": ["desayuno"],
  },
  {
    "name": "Arepas de Quinoa",
    "videoUrl": "assets/video/arepasQuinoa.mp4",
    "imageUrl": "assets/images/arepasQuinoa.png",
    "ingredientCategory": ["quinua", "avena", "zanahoria", "pollo", "aguacate"],
    "recipeType": ["almuerzo", "cena"],
  },
  {
    "name": "Estofado de Garbanzo",
    "videoUrl": "assets/video/estofadoGarbanzo.mp4",
    "imageUrl": "assets/images/estofadoGarbanzo.png",
    "ingredientCategory": ["garbanzo", "zanahoria"],
    "recipeType": ["almuerzo", "cena"],
  },
];

/*
List<Map<String, dynamic>> healthyRecipes = [
  {
    'name': 'Mayonesa',
    'videoUrl': 'assets/video/mayonesa1.mp4',
    'imageUrl': 'assets/images/mayonesa1.png',
    'ingredientCategory': [IngredientCategory.mayonesa],
    'recipeType': [RecipeType.salsa],
  },
  {
    'name': 'Pancake de Remolacha',
    'videoUrl': 'assets/video/pancakeRemolacha.mp4',
    'imageUrl': 'assets/images/remolacha.jpg',
    'ingredientCategory': [
      IngredientCategory.tortitas,
      IngredientCategory.avena,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Burrito con Atún',
    'videoUrl': 'assets/video/burritoAtun.mp4',
    'imageUrl': 'assets/images/burritoAtun.png',
    'ingredientCategory': [
      IngredientCategory.aguacate,
      IngredientCategory.atun,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Ensalada con Pollo',
    'videoUrl': 'assets/video/ensaladaPollo.mp4',
    'imageUrl': 'assets/images/ensaladaPollo.png',
    'ingredientCategory': [IngredientCategory.huevo, IngredientCategory.pollo],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Wrap de espinaca',
    'videoUrl': 'assets/video/wrapEspinaca.mp4',
    'imageUrl': 'assets/images/wrapEspinaca.jpg',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.espinaca,
      IngredientCategory.tortitas,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Pasta con atún',
    'videoUrl': 'assets/video/pastayAtun.mp4',
    'imageUrl': 'assets/images/pastayAtun.jpg',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.huevo,
      IngredientCategory.atun,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Huevo y Atun',
    'videoUrl': 'assets/video/huevoyAtun.mp4',
    'imageUrl': 'assets/images/huevoyAtun.png',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.huevo,
      IngredientCategory.atun,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Tortilla de avena',
    'videoUrl': 'assets/video/tortillaAvena.mp4',
    'imageUrl': 'assets/images/tortillaAvena.png',
    'ingredientCategory': [
      IngredientCategory.tortitas,
      IngredientCategory.huevo,
      IngredientCategory.avena,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Wrap Espinaca y Huevo',
    'videoUrl': 'assets/video/wrapEspinacaHuevo.mp4',
    'imageUrl': 'assets/images/wrapEspinacaHuevo.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.huevo,
      IngredientCategory.espinaca,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tostada con huevo',
    'videoUrl': 'assets/video/tostadaHuevo.mp4',
    'imageUrl': 'assets/images/tostadaHuevo.jpg',
    'ingredientCategory': [
      IngredientCategory.tostada,
      IngredientCategory.huevo,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Atún con pepino',
    'videoUrl': 'assets/video/atunconPepino.mp4',
    'imageUrl': 'assets/images/atunconPepino.png',
    'ingredientCategory': [
      IngredientCategory.atun,
      IngredientCategory.pepino,
      IngredientCategory.aguacate,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.cena, RecipeType.almuerzo],
  },
  {
    'name': 'Tostada con huevo duro',
    'videoUrl': 'assets/video/tostadaHuevoduro.mp4',
    'imageUrl': 'assets/images/tostadaHuevoduro.png',
    'ingredientCategory': [
      IngredientCategory.tostada,
      IngredientCategory.huevo,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Tortilla de zanahoria',
    'videoUrl': 'assets/video/tortillaZanahoria.mp4',
    'imageUrl': 'assets/images/tortillaZanahoria.png',
    'ingredientCategory': [
      IngredientCategory.zanahoria,
      IngredientCategory.huevo,
      IngredientCategory.platano,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Yogurt con manzana',
    'videoUrl': 'assets/video/yoguryManzana.mp4',
    'imageUrl': 'assets/images/yoguryManzana.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.yogurGriego,
      IngredientCategory.manzana,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.postre],
  },
  {
    'name': 'Papas fritas saludables',
    'videoUrl': 'assets/video/papasSaludables.mp4',
    'imageUrl': 'assets/images/papasSaludables.png',
    'ingredientCategory': [IngredientCategory.mayonesa],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Wrap de pollo',
    'videoUrl': 'assets/video/wrapPollo.mp4',
    'imageUrl': 'assets/images/wrapPollo.jpg',
    'ingredientCategory': [
      IngredientCategory.pollo,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Atún con Huevo duro',
    'videoUrl': 'assets/video/atunyHuevoDuro.mp4',
    'imageUrl': 'assets/images/atunyHuevoDuro.png',
    'ingredientCategory': [IngredientCategory.atun, IngredientCategory.huevo],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Atún con pepino',
    'videoUrl': 'assets/video/atunyPepino.mp4',
    'imageUrl': 'assets/images/atunyPepino.png',
    'ingredientCategory': [
      IngredientCategory.atun,
      IngredientCategory.aguacate,
      IngredientCategory.pepino,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Yogurt griego',
    'videoUrl': 'assets/video/yogurtGriego.mp4',
    'imageUrl': 'assets/images/yogurtGriego.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.postre],
  },
  {
    'name': 'Arroz de coliflor',
    'videoUrl': 'assets/video/arrozColiflor.mp4',
    'imageUrl': 'assets/images/arrozColiflor.png',
    'ingredientCategory': [IngredientCategory.brocoli],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Yogurt con Banana/Melon',
    'videoUrl': 'assets/video/yogurBananaMelon.mp4',
    'imageUrl': 'assets/images/yogurBananaMelon.png',
    'ingredientCategory': [
      IngredientCategory.yogurGriego,
      IngredientCategory.avena,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.postre],
  },
  {
    'name': 'Wrap de Brócoli',
    'videoUrl': 'assets/video/wrapBrocoli.mp4',
    'imageUrl': 'assets/images/wrapBrocoli.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.brocoli,
      IngredientCategory.tortitas,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Plátano con Huevo',
    'videoUrl': 'assets/video/platanoHuevo.mp4',
    'imageUrl': 'assets/images/platanoHuevo.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Manzana revuelta de Avena',
    'videoUrl': 'assets/video/manzanaenAvena.mp4',
    'imageUrl': 'assets/images/manzanaenAvena.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.huevo,
      IngredientCategory.manzana,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.postre],
  },
  {
    'name': 'Pescado con pepino',
    'videoUrl': 'assets/video/pescadoyPepino.mp4',
    'imageUrl': 'assets/images/pescadoyPepino.png',
    'ingredientCategory': [
      IngredientCategory.pescado,
      IngredientCategory.pepino,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Platano asado con huevos',
    'videoUrl': 'assets/video/platanoasadoHuevos.mp4',
    'imageUrl': 'assets/images/platanoasadoHuevos.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.platano,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Mayonesa 2',
    'videoUrl': 'assets/video/mayonesa2.mp4', // Corregido .mp4
    'imageUrl': 'assets/images/mayonesa2.png',
    'ingredientCategory': [IngredientCategory.mayonesa],
    'recipeType': [RecipeType.salsa],
  },
  {
    'name': 'Pancake de manzana',
    'videoUrl': 'assets/video/pancakeManzana.mp4',
    'imageUrl': 'assets/images/pancakeManzana.png',
    'ingredientCategory': [
      IngredientCategory.manzana,
      IngredientCategory.avena,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Ensalada de Huevo',
    'videoUrl': 'assets/video/ensaladaHuevo.mp4',
    'imageUrl': 'assets/images/ensaladaHuevo.png',
    'ingredientCategory': [IngredientCategory.huevo],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Mayonesa 3',
    'videoUrl': 'assets/video/mayonesa3.mp4',
    'imageUrl': 'assets/images/mayonesa3.png',
    'ingredientCategory': [IngredientCategory.mayonesa],
    'recipeType': [RecipeType.salsa],
  },
  {
    'name': 'Pasta con Pollo',
    'videoUrl': 'assets/video/pastaPollo.mp4',
    'imageUrl': 'assets/images/pastaPollo.jpg',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.pollo,
      IngredientCategory.brocoli,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Burrito de Huevo duro',
    'videoUrl': 'assets/video/burritoHuevoDuro.mp4',
    'imageUrl': 'assets/images/burritoHuevoDuro.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.burrito,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Pancake de Espinaca entera',
    'videoUrl': 'assets/video/pancakeEspinacaEntera.mp4',
    'imageUrl': 'assets/images/pancakeEspinacaEntera.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.espinaca,
      IngredientCategory.avena,
      IngredientCategory.tortitas,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Pasta con Atún',
    'videoUrl': 'assets/video/pastaAtun.mp4',
    'imageUrl': 'assets/images/pastaAtun.png',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.atun,
      IngredientCategory.aguacate,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Huevo y Calabacin',
    'videoUrl': 'assets/video/huevoCalabacin.mp4',
    'imageUrl': 'assets/images/huevoCalabacin.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.zanahoria,
      IngredientCategory.calabacin,
      IngredientCategory.tortitas,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tostada de Atún',
    'videoUrl': 'assets/video/tostadaAtun.mp4',
    'imageUrl': 'assets/images/tostadaAtun.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.atun,
      IngredientCategory.yogurGriego,
      IngredientCategory.aguacate,
      IngredientCategory.tostada,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tostada de Espinaca',
    'videoUrl': 'assets/video/tostadaEspinaca.mp4',
    'imageUrl': 'assets/images/tostadaEspinaca.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.espinaca,
      IngredientCategory.tostada,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Wrap con Tortilla de huevo',
    'videoUrl': 'assets/video/wrapTortillaHuevo.mp4',
    'imageUrl': 'assets/images/wrapTortillaHuevo.png',
    'ingredientCategory': [
      IngredientCategory.espinaca,
      IngredientCategory.huevo,
      IngredientCategory.aguacate,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Brócoli aplastado',
    'videoUrl': 'assets/video/brocoliAplastado.mp4',
    'imageUrl': 'assets/images/brocoliAplastado.png',
    'ingredientCategory': [IngredientCategory.brocoli],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Plátano con Atún',
    'videoUrl': 'assets/video/platanoconAtun.mp4',
    'imageUrl': 'assets/images/platanoconAtun.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.pepino,
      IngredientCategory.atun,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Tortilla de Coliflor',
    'videoUrl': 'assets/video/tortaColiflor.mp4',
    'imageUrl': 'assets/images/tortaColiflor.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.cena, RecipeType.almuerzo],
  },
  {
    'name': 'Tortilla de Avena pura',
    'videoUrl': 'assets/video/tortillaAvenapura.mp4',
    'imageUrl': 'assets/images/tortillaAvenapura.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.aguacate,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Arepa de Avena',
    'videoUrl': 'assets/video/arepaAvenaV.mp4',
    'imageUrl': 'assets/images/arepaAvenaI.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.atun,
      IngredientCategory.mostaza,
      IngredientCategory.yogurGriego,
      IngredientCategory.avena,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Empanada de Manzana',
    'videoUrl': 'assets/video/empanadaManzana.mp4',
    'imageUrl': 'assets/images/empanadaManzanaI.png',
    'ingredientCategory': [
      IngredientCategory.manzana,
      IngredientCategory.huevo,
      IngredientCategory.tostada,
    ],
    'recipeType': [RecipeType.postre, RecipeType.desayuno],
  },
  {
    'name': 'Flautas de Pollo',
    'videoUrl': 'assets/video/flautasPollo.mp4',
    'imageUrl': 'assets/images/flautasPolloI.png',
    'ingredientCategory': [
      IngredientCategory.pollo,
      IngredientCategory.yogurGriego,
      IngredientCategory.mostaza,
      IngredientCategory.burrito,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Guacamole para Tostada',
    'videoUrl': 'assets/video/guacamoleTostada.mp4',
    'imageUrl': 'assets/images/guacamoleTostadaI.png',
    'ingredientCategory': [
      IngredientCategory.aguacate,
      IngredientCategory.garbanzo,
      IngredientCategory.tostada,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.salsa],
  },
  {
    'name': 'Tortilla de Atún',
    'videoUrl': 'assets/video/tortillaAtun.mp4',
    'imageUrl': 'assets/images/tortillaAtunI.png',
    'ingredientCategory': [
      IngredientCategory.atun,
      IngredientCategory.avena,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Torta de brócoli',
    'videoUrl': 'assets/video/tortitaBlocoliV.mp4',
    'imageUrl': 'assets/images/tortitaBrocoliI.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.huevo,
      IngredientCategory.avena,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Tostada de atún y huevo',
    'videoUrl': 'assets/video/tostadaHuevAtunV.mp4',
    'imageUrl': 'assets/images/tostadaHuevAtunI.png',
    'ingredientCategory': [
      IngredientCategory.atun,
      IngredientCategory.huevo,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Yogurt griego con Arroz',
    'videoUrl': 'assets/video/yogurtArrozV.mp4',
    'imageUrl': 'assets/images/yogurtArrozI.png',
    'ingredientCategory': [IngredientCategory.yogurGriego],
    'recipeType': [RecipeType.postre],
  },
  {
    'name': 'Yogurt Griego y Zanahoria',
    'videoUrl': 'assets/video/yogurtZanahoriaV.mp4',
    'imageUrl': 'assets/images/yogurtZanahoriaI.png',
    'ingredientCategory': [
      IngredientCategory.yogurGriego,
      IngredientCategory.manzana,
      IngredientCategory.avena,
      IngredientCategory.zanahoria,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.postre],
  },
  {
    'name': 'Tortilla de Coliflor (2)',
    'videoUrl': 'assets/video/tortitasColiflor.mp4',
    'imageUrl': 'assets/images/tortitasColiflor.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.huevo,
      IngredientCategory.tortitas,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Pollo en Salsa',
    'videoUrl': 'assets/video/polloenSalsa.mp4',
    'imageUrl': 'assets/images/polloenSalsa.png',
    'ingredientCategory': [IngredientCategory.pollo],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Tortilla de Linaza',
    'videoUrl': 'assets/video/tortillaLinaza.mp4',
    'imageUrl': 'assets/images/tortillaLinaza.png',
    'ingredientCategory': [IngredientCategory.linaza],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tostada con Espinaca',
    'videoUrl': 'assets/video/tostadaconEspinaca.mp4',
    'imageUrl': 'assets/images/tostadaconEspinaca.png',
    'ingredientCategory': [
      IngredientCategory.tostada,
      IngredientCategory.huevo,
      IngredientCategory.espinaca,
      IngredientCategory.airFryer,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Pizza de Coliflor',
    'videoUrl': 'assets/video/pizzaColiflor.mp4',
    'imageUrl': 'assets/images/pizzaColiflor.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.avena,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Chips de Platano',
    'videoUrl': 'assets/video/platanitos.mp4',
    'imageUrl': 'assets/images/platanitos.png',
    'ingredientCategory': [
      IngredientCategory.aguacate,
      IngredientCategory.platano,
      IngredientCategory.airFryer,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Quinua con Atún',
    'videoUrl': 'assets/video/quinuaconAtun.mp4',
    'imageUrl': 'assets/images/quinuaconAtun.png',
    'ingredientCategory': [
      IngredientCategory.atun,
      IngredientCategory.aguacate,
      IngredientCategory.huevo,
      IngredientCategory.quinua,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Tortilla de Atún y Zanahoria',
    'videoUrl': 'assets/video/tortaAtunyZanahoria.mp4',
    'imageUrl': 'assets/images/tortaAtunyZanahoria.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.atun,
      IngredientCategory.zanahoria,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Tortilla de lenteja',
    'videoUrl': 'assets/video/tortitaLentejas.mp4',
    'imageUrl': 'assets/images/tortitaLentejas.png',
    'ingredientCategory': [IngredientCategory.lentejas],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Pasta con espinaca',
    'videoUrl': 'assets/video/pastayEspinaca.mp4',
    'imageUrl': 'assets/images/pastayEspinaca.png',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.espinaca,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Pasta con Coliflor',
    'videoUrl': 'assets/video/pastayColiflor.mp4',
    'imageUrl': 'assets/images/pastayColiflor.png',
    'ingredientCategory': [
      IngredientCategory.pasta,
      IngredientCategory.brocoli,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Pan de Lentejas',
    'videoUrl': 'assets/video/panLentejas.mp4',
    'imageUrl': 'assets/images/panLentejas.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.lentejas,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tortitas de Brócoli',
    'videoUrl': 'assets/video/pancitoBrocoli_Queso.mp4',
    'imageUrl': 'assets/images/pancitoBrocoli_Queso.png',
    'ingredientCategory': [IngredientCategory.brocoli],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Burrito con Brócoli',
    'videoUrl': 'assets/video/burritoConBrocoli.mp4',
    'imageUrl': 'assets/images/burritoConBrocoli.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.huevo,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Burrito cuadrado',
    'videoUrl': 'assets/video/burritoCuadrado.mp4',
    'imageUrl': 'assets/images/burritoCuadrado.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Burrito con espinacas',
    'videoUrl': 'assets/video/burritodeEspinacas.mp4',
    'imageUrl': 'assets/images/burritodeEspinacas.png',
    'ingredientCategory': [
      IngredientCategory.espinaca,
      IngredientCategory.atun,
      IngredientCategory.huevo,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Burrito en pedazos',
    'videoUrl': 'assets/video/burritoPedazos.mp4',
    'imageUrl': 'assets/images/burritoPedazos.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.airFryer,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Ensalada de garbanzos',
    'videoUrl': 'assets/video/ensaladaGarbanzos.mp4',
    'imageUrl': 'assets/images/ensaladaGarbanzos.png',
    'ingredientCategory': [
      IngredientCategory.garbanzo,
      IngredientCategory.zanahoria,
      IngredientCategory.atun,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Wrap de atún cremoso',
    'videoUrl': 'assets/video/wrap_de_atun_cremoso.mp4',
    'imageUrl': 'assets/images/wrap_de_atun_cremoso.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.atun,
      IngredientCategory.quesoCrema,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Arepa de quinua',
    'videoUrl': 'assets/video/arepadequinua.mp4',
    'imageUrl': 'assets/images/arepadequinua.png',
    'ingredientCategory': [
      IngredientCategory.aguacate,
      IngredientCategory.yogurGriego,
      IngredientCategory.pollo,
      IngredientCategory.zanahoria,
      IngredientCategory.quinua,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Arroz de coliflor pintado',
    'videoUrl': 'assets/video/arroz_de_coliflorPintado.mp4',
    'imageUrl': 'assets/images/arroz_de_coliflorPintado.png',
    'ingredientCategory': [
      IngredientCategory.brocoli,
      IngredientCategory.zanahoria,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Pan de espinaca y avena',
    'videoUrl': 'assets/video/pan_de_espinaca_y_avena.mp4',
    'imageUrl': 'assets/images/pan_de_espinaca_y_avena.png',
    'ingredientCategory': [
      IngredientCategory.espinaca,
      IngredientCategory.avena,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Wrap de pollo cremoso',
    'videoUrl': 'assets/video/wrap_de_pollo_cremoso.mp4',
    'imageUrl': 'assets/images/wrap_de_pollo_cremoso.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.pollo,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Hotcakes esponjosos de avena',
    'videoUrl': 'assets/video/hotcakes_esponjosos_de_avena.mp4',
    'imageUrl': 'assets/images/hotcakes_esponjosos_de_avena.png',
    'ingredientCategory': [IngredientCategory.avena, IngredientCategory.huevo],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Pizza de calabacin',
    'videoUrl': 'assets/video/pizza_de_calabacin.mp4',
    'imageUrl': 'assets/images/pizza_de_calabacin.png',
    'ingredientCategory': [
      IngredientCategory.calabacin,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Pan de linaza',
    'videoUrl': 'assets/video/pan_de_linaza.mp4',
    'imageUrl': 'assets/images/pan_de_linaza.png',
    'ingredientCategory': [IngredientCategory.linaza, IngredientCategory.huevo],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Pastel de Yogurt',
    'videoUrl': 'assets/video/pastel_de_yogurt.mp4',
    'imageUrl': 'assets/images/pastel_de_yogurt.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.huevo,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.postre],
  },
  {
    'name': 'Ensalada de pepino cremoso',
    'videoUrl': 'assets/video/ensalada_pepino.mp4',
    'imageUrl': 'assets/images/ensalada_pepino.png',
    'ingredientCategory': [
      IngredientCategory.pepino,
      IngredientCategory.aguacate,
      IngredientCategory.atun,
      IngredientCategory.quesoCrema,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Mayonesa sin aceite',
    'videoUrl': 'assets/video/mayonesa_sin_aceite.mp4',
    'imageUrl': 'assets/images/mayonesa_sin_aceite.png',
    'ingredientCategory': [IngredientCategory.mayonesa],
    'recipeType': [RecipeType.salsa],
  },
  {
    'name': 'Croquetas de calabacin',
    'videoUrl': 'assets/video/croquetas_calabacin.mp4',
    'imageUrl': 'assets/images/croquetas_calabacin.png',
    'ingredientCategory': [
      IngredientCategory.calabacin,
      IngredientCategory.avena,
      IngredientCategory.huevo,
      IngredientCategory.tortitas,
    ],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Wrap de Atún', // Corregido nombre
    'videoUrl': 'assets/video/wrapdeAtun.mp4',
    'imageUrl': 'assets/images/wrapdeAtun.png',
    'ingredientCategory': [IngredientCategory.atun, IngredientCategory.huevo],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Mini tortillas de zanahoria',
    'videoUrl': 'assets/video/miniTortillas_zanahoria.mp4',
    'imageUrl': 'assets/images/miniTortillas_zanahoria.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.zanahoria,
      IngredientCategory.pollo,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Wrap de Quinua',
    'videoUrl': 'assets/video/wrapdeQuinua.mp4',
    'imageUrl': 'assets/images/wrapdeQuinua.png',
    'ingredientCategory': [
      IngredientCategory.quinua,
      IngredientCategory.huevo,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Quinua con huevo',
    'videoUrl': 'assets/video/quinoaconHuevo.mp4',
    'imageUrl': 'assets/images/quinoaconHuevo.png',
    'ingredientCategory': [
      IngredientCategory.quinua,
      IngredientCategory.brocoli,
      IngredientCategory.zanahoria,
      IngredientCategory.calabacin,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Platano y huevo',
    'videoUrl': 'assets/video/platanoyHuevo.mp4',
    'imageUrl': 'assets/images/platanoyHuevo.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Patacones saludables',
    'videoUrl': 'assets/video/pataconesSaludables.mp4',
    'imageUrl': 'assets/images/pataconesSaludables.png',
    'ingredientCategory': [
      IngredientCategory.airFryer,
      IngredientCategory.platano,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Pan keto',
    'videoUrl': 'assets/video/panKeto.mp4',
    'imageUrl': 'assets/images/panKeto.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Ensalada de Lechuga y Huevos',
    'videoUrl': 'assets/video/ensaladaLechugaHuevos.mp4',
    'imageUrl': 'assets/images/ensaladaLechugaHuevos.png',
    'ingredientCategory': [IngredientCategory.huevo],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Mayonesa para diabeticos',
    'videoUrl': 'assets/video/MayonesaDiabeticos.mp4',
    'imageUrl': 'assets/images/MayonesaDiabeticos.png',
    'ingredientCategory': [
      IngredientCategory.aguacate,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.salsa],
  },
  {
    'name': 'Arepa de Plátano',
    'videoUrl': 'assets/video/arepaPlatano.mp4',
    'imageUrl': 'assets/images/arepaPlatano.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.zanahoria,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Tostadas de zanahoria',
    'videoUrl': 'assets/video/tostadasZanahoria.mp4',
    'imageUrl': 'assets/images/tostadasZanahoria.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.zanahoria,
      IngredientCategory.quesoCrema,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Huevos fritos y platano',
    'videoUrl': 'assets/video/huevosFritosyPlatano.mp4',
    'imageUrl': 'assets/images/huevosFritosyPlatano.png',
    'ingredientCategory': [
      IngredientCategory.airFryer,
      IngredientCategory.aguacate,
      IngredientCategory.huevo,
      IngredientCategory.platano,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Roll de Aguacate',
    'videoUrl': 'assets/video/rollAguacate.mp4',
    'imageUrl': 'assets/images/rollAguacate.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.aguacate,
      IngredientCategory.huevo,
      IngredientCategory.pollo,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Pancakes de plátano',
    'videoUrl': 'assets/video/pancakesPlatano.mp4',
    'imageUrl': 'assets/images/pancakesPlatano.png',
    'ingredientCategory': [
      IngredientCategory.platano,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Tortillas de quinoa y remolacha',
    'videoUrl': 'assets/video/TortillasQuinoaRemolacha.mp4',
    'imageUrl': 'assets/images/TortillasQuinoaRemolacha.png',
    'ingredientCategory': [
      IngredientCategory.burrito,
      IngredientCategory.quinua,
      IngredientCategory.remolacha,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Tostada de espinaca y avena',
    'videoUrl': 'assets/video/tostadaEspinacaAvena.mp4',
    'imageUrl': 'assets/images/tostadaEspinacaAvena.png',
    'ingredientCategory': [
      IngredientCategory.espinaca,
      IngredientCategory.avena,
      IngredientCategory.huevo,
      IngredientCategory.tostada,
    ],
    'recipeType': [RecipeType.desayuno],
  },
  {
    'name': 'Arepas de Quinoa',
    'videoUrl': 'assets/video/arepasQuinoa.mp4',
    'imageUrl': 'assets/images/arepasQuinoa.png',
    'ingredientCategory': [
      IngredientCategory.quinua,
      IngredientCategory.avena,
      IngredientCategory.zanahoria,
      IngredientCategory.pollo,
      IngredientCategory.aguacate,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Estofado de Garbanzo',
    'videoUrl': 'assets/video/estofadoGarbanzo.mp4',
    'imageUrl': 'assets/images/estofadoGarbanzo.png',
    'ingredientCategory': [
      IngredientCategory.garbanzo,
      IngredientCategory.huevo,
    ],
    'recipeType': [RecipeType.almuerzo],
  },
  {
    'name': 'Torta de Zanahoria y Guineo',
    'videoUrl': 'assets/video/tortaZanahoriayGuineo.mp4',
    'imageUrl': 'assets/images/tortaZanahoriayGuineo.png',
    'ingredientCategory': [
      IngredientCategory.avena,
      IngredientCategory.platano,
      IngredientCategory.zanahoria,
      IngredientCategory.huevo,
      IngredientCategory.yogurGriego,
    ],
    'recipeType': [RecipeType.postre, RecipeType.desayuno],
  },
  {
    'name': 'Pizza de atún',
    'videoUrl': 'assets/video/pizzadeAtun.mp4',
    'imageUrl': 'assets/images/pizzadeAtun.png',
    'ingredientCategory': [IngredientCategory.huevo, IngredientCategory.atun],
    'recipeType': [RecipeType.cena],
  },
  {
    'name': 'Ensalada de frejol y Quinoa',
    'videoUrl': 'assets/video/ensaladaFrejolQuinua.mp4',
    'imageUrl': 'assets/images/ensaladaFrejolQuinua.png',
    'ingredientCategory': [
      IngredientCategory.frejol,
      IngredientCategory.quinua,
    ],
    'recipeType': [RecipeType.almuerzo, RecipeType.cena],
  },
  {
    'name': 'Huevo con Verduras',
    'videoUrl': 'assets/video/huevoconVerduras.mp4',
    'imageUrl': 'assets/images/huevoconVerduras.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.burrito,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
  {
    'name': 'Pan nube proteico',
    'videoUrl': 'assets/video/panNubeProteico.mp4',
    'imageUrl': 'assets/images/panNubeProteico.png',
    'ingredientCategory': [
      IngredientCategory.huevo,
      IngredientCategory.quesoCrema,
    ],
    'recipeType': [RecipeType.desayuno, RecipeType.cena],
  },
];

*/
